### ISSUE TITLE
Feature Request: Support dynamic mapping

### ISSUE THREAD

**Issue by samdjstevens** [FriendsOfSymfony/FOSElasticaBundle#1223]
Hey, 

I'm new to Elasticsearch, so I don't know if this is a rare need/bad practice, but I was looking for a way for mapping to be dynamic (from PHP execution), rather than just defined in the YAML.

To briefly summarise my specific use-case, I want to map extra fields to a type, if the entity for that type implements a certain interface.

Following the method for [dynamic property setting](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/cookbook/pre-transform-event.md), I propose that the `IndexResetEvent` event fired before the index map is built be given the `IndexConfig` instance, and to add the ability to mutate the config on this class. 

Then, in my app code I can listen for this event, and modify the index config and add the extra mapping properties.

I'm more than happy to submit a PR for this if this would be something you think is a good idea and would benefit the bundle.

Cheers

**Comment by XWB** [comment]
We do support dynamic mapping, isn't that what you're looking for?

https://www.elastic.co/guide/en/elasticsearch/guide/current/dynamic-mapping.html

**Comment by samdjstevens** [comment]
Hi  - I'm not 100% sure from that link, but would this work with the [completion](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html) type? 

I am under the impression that this `type: completion` has to be explicitly defined before indexing documents - but not sure if that's the case.

**Comment by XWB** [comment]
I have no experience with the completion type. What happens if you add `type: completion` to your mapping config?

**Comment by Tobion** [comment]
Yes `completion` should be defined before indexing the document because the auto-detection of property mappings will not apply completion mapping to new properties.

You can either explicitly define the completion mapping on your type if you know the fields.
Or alternatively, doing it dynamically without knowing the exact document structure, also works by using dynamic templates: https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html
For example you can specify all fields with a certain name, should be mapped as `completion` type by default.
