### ISSUE TITLE
How to avoid querying database while using FOSElasticaBundle

### ISSUE THREAD

**Issue by webtsx** [FriendsOfSymfony/FOSElasticaBundle#1282]
Hello,
I would like ask you how to avoid querying database while fetching records using FOSElasticaBundle. 
All necessary information are collected in Elasticsearch and there is no need to query database, but there are currently 11 queries to the database on each request. 

Thank you in advance.

**Comment by The-Don-Himself** [comment]
All the information is in the docs folder https://github.com/FriendsOfSymfony/FOSElasticaBundle/tree/master/Resources/doc, including how to achieve this. and more.


Please close this as it's not an issue.

**Comment by NAYZO** [comment]
Hello @The-Don-Himself, i am facing the same issue here, could you please be more specific, as I looked into the doc and I still can't find how I could avoid database queries.

Thanks in advance for your reply,

**Comment by The-Don-Himself** [comment]
I will submit a PR soon to improve the docs with regards to this issue. Because, going through the docs, it is there, first line.

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/usage.md

````
Basic Searching with a Finder

The most useful searching method is to use a finder defined by the type configuration. A finder will return results that have been hydrated by the configured persistence backend....
````
The hydration by the persistence backend part implies a database query(s).

So implicitly, if you don't want to hydrate the results (i.e get back raw arrays from elasticsearch), then you must not use the finder method but search the index directly, which means more work in building the query using the underlying Ruflin/Elastica library. 

I'll give you an example, say you created a users_index and users_type.

This index would be registered under fos_elastica.index.users_index.users_type get the index as follows

````
$elastica_index = $this->get('fos_elastica.index.users_index.users_type');
````

Now, follow the example under the advanced usage

````
$boolQuery = new \Elastica\Query\BoolQuery();

$fieldQuery = new \Elastica\Query\Match();
$fieldQuery->setFieldQuery('username', 'The_Don_Himself');
$fieldQuery->setFieldFuzziness('username', 2); // Will match e.g he_Don_Himself, the_Don_Himsel, the_Don_imself
$boolQuery->addMust($fieldQuery);

$rolesQuery = new \Elastica\Query\Terms();
$rolesQuery->setTerms('roles', array('ROLE_ADMIN'));
$boolQuery->addMust($tagsQuery);

$enabledQuery = new \Elastica\Query\Terms();
$enabledQuery->setTerms('enabled', array(true));
$boolQuery->addMust($enabledQuery);

$emailQuery = new \Elastica\Query\Match();
$emailQuery->setFieldQuery('email', 'gmail.com');
$boolQuery->addShould($emailQuery);

$util = new \Elastica\Util()

$dateConverted = $util->convertDateTimeObject(new \DateTime());
$lastLoginBeforeQuery = new \Elastica\Query\Range();
$lastLoginBeforeQuery->addField('last_login', array('lte' => $dateConverted));
$boolQuery->addShould($lastLoginBeforeQuery);

$elastica_search = $elastica_index->search($boolQuery);

$results = $elastica_search->getResults();
$count = $elastica_search->count();
$totalHits = $elastica_search->getTotalHits();
$totalTime = $elastica_search->getTotalTime();

````
 
I hope this is a comprehensive enough answer, I submit a PR to add this example under the advanced usage. Go through the docs and examples in Ruflin/Elastica to see all possible examples of queries you can execute, I've used the following in the past

````
use Elastica\Aggregation\GeohashGrid;
use Elastica\Aggregation\TopHits;
use Elastica\Query;
use Elastica\Query\BoolQuery;
use Elastica\Query\GeoBoundingBox;
use Elastica\Query\GeoDistance;
use Elastica\Query\GeoShapeProvided;
use Elastica\Query\Match;
use Elastica\Query\Nested;
use Elastica\Query\Range;
use Elastica\Query\Terms;
use Elastica\Util;
````

Regards,

**Comment by hatem20** [comment]
@The-Don-Himself is there any other way since search method is protected and i can only use find?

**Comment by murilozilli** [comment]
Updating links posted here:
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/usage.md
