### ISSUE TITLE
Indexing OneToMany Relations

### ISSUE THREAD

**Issue by berny46** [FriendsOfSymfony/FOSElasticaBundle#1296]
Hi everyone,
so these are my first Steps with elasticsearch and FosElastica and I have problems with converting OneToMany relations in my Entities to the desired index.

I have three (example) Tables, "band", "album" and "track". There is a bidirectional OneToMany relation from  band<=>album and album<=>track. This mapping:

    fos_elastica:
        clients:
            default:
                host: "%fos_elastica.host%"
                port: "%fos_elastica.port%"
        indexes:
            music:
                finder: ~
                client: default
                types:
                    band:
                        mappings:
                            id:
                                type: integer
                            name: ~
                            albums:
                               type: nested
                               properties:
                                  id: ~
                                  albumTitle: ~
                                  tracks:
                                     type: nested
                                     properties:
                                        id: ~
                                        trackTitle: ~
    
                        persistence:
                            driver: orm
                            model: AppBundle\Entity\Band
                            finder: ~
                            provider: ~
                            listener:
                                logger: true
gives me only one indexed document:

    {
      "took" : 7,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "skipped" : 0,
        "failed" : 0
      },
      "hits" : {
        "total" : 1,
        "max_score" : 1.0,
        "hits" : [
          {
            "_index" : "music",
            "_type" : "band",
            "_id" : "1",
            "_score" : 1.0,
            "_source" : {
              "id" : 1,
              "name" : "Queen",
              "albums" : [
                {
                  "id" : 1,
                  "albumTitle" : "The Works",
                  "tracks" : [
                    {
                      "id" : 1,
                      "trackTitle" : "Radio Ga Ga"
                    },
                    {
                      "id" : 2,
                      "trackTitle" : "Tear It Up"
                    }
                  ]
                },
                {
                  "id" : 2,
                  "albumTitle" : "A Kind of Magic",
                  "tracks" : [
                    {
                      "id" : 3,
                      "trackTitle" : "One Vision"
                    },
                    {
                      "id" : 4,
                      "trackTitle" : "A Kind of Magic"
                    }
                  ]
                }
              ]
            }
          }
        ]
      }
    }

But what i'd like to achive, is an index with four documents, like this:

    SELECT b.id, b.name, a.id as album_id, a.album_title, t.id AS track_id, t.track_title, t.track_number FROM band b
    LEFT OUTER JOIN album a ON b.id = a.band_id
    LEFT OUTER JOIN track t ON a.id = t.album_id

| id | name | album_id | album_title | track_title | track_number | 
| -: | - | -: | - | - | -: | 
| 1 | Queen | 1 | The Works | Radio Ga Ga | 1 | 
| 1 | Queen | 1 | The Works | Tear It Up | 2 | 
| 1 | Queen | 2 | A Kind of Magic | One Vision | 1 | 
| 1 | Queen | 2 | A Kind of Magic | A Kind of Magic | 2 | 

Could someone point me in the right direction on what steps to perform with FosElastica to achive an indexing like this?

Thanks
Chris

**Comment by The-Don-Himself** [comment]
Hi @berny46 , it seems like you might need to go over Elasticsearch basics first, in which case heading over to [Elasticsearch forums](https://discuss.elastic.co) would yield better results for you as this library is for sending/syncing doctrine to elasticsearch and querying the same.

That said, a little help from me would be to say that your query and mapping is 100% okay. The issue is that you are mixing relational DB thinking (MySQL, Postgres, etc) with Document DBs (MongoDB, Elasticsearch).

RDMS would advocate that you don't repeat data and use joins instead, while Document DB's encourage you to embed and duplicate your data. Please, please , please, read this blog post http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/. It's a very unfair analysis on MongoDB since it was all the author's fault but it opens up people's mind to how Document DB's can shoot you in the foot.

I see two options for your use case :- 
1.) Do as you have done, then, unfold the albums array into individual objects, same to the tracks. This is very very ugly especially with hundreds of data and is similar to what can be done with MongoDB's unwind function.
2.) Realize that perhaps a Document database is not the best tool for your Relational data, if search is the one and only thing you want to bring in Elasticsearch for you can consider string indexes in your RDBMS or better yet consider a graph database instead. There is a very interesting one I use called [JanusGraph](https://github.com/JanusGraph/janusgraph) by IBM and Google, it can use Elasticsearch as a search engine so you can still get its benefits, I'm also writing a[ PHP-OGM library](https://github.com/The-Don-Himself/gremlin-ogm) for it but it's far from finished.

**Comment by berny46** [comment]
So i figured out how to solve the problem above. I created a BandRepository Call like this:

    namespace AppBundle\Entity\Repository;

    use Doctrine\ORM\EntityRepository;

    class BandRepository extends EntityRepository
    {
        public function findAllRelations()
        {

            $sql = 'SELECT b.id, b.name, a.id as album_id, a.album_title, t.id AS track_id, t.track_title, t.track_number
                    FROM band b
                    LEFT OUTER JOIN album a ON b.id = a.band_id
                    LEFT OUTER JOIN track t ON a.id = t.album_id';

            return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();
        }
    }
a Band Provider:

    namespace AppBundle\Provider;

    use AppBundle\Entity\Band;
    use Closure;
    use Doctrine\ORM\EntityManager;
    use Elastica\Document;
    use Elastica\Type;
    use FOS\ElasticaBundle\Provider\ProviderInterface;

    class BandProvider implements ProviderInterface
    {
        protected $bandType;
        protected $em;

        public function __construct(Type $bandType, EntityManager $em)
        {
            $this->bandType = $bandType;
            $this->em = $em;
        }


        public function populate(Closure $loggerClosure = null, array $options = [])
        {
            $indexData = $this->em->getRepository(Band::class)->findAllRelations();

            $i = 1;
            foreach ($indexData as $index) {
                $document = new Document();
                $document->setId($i++);
                $document->setData($index);

                $this->bandType->addDocuments([$document]);
            }
        }
    }
changed the fos_elastica config:

    fos_elastica:
        clients:
            default:
                host: "%fos_elastica.host%"
                port: "%fos_elastica.port%"
        indexes:
            music:
                finder: ~
                client: default
                types:
                    band:
                        mappings: ~
                        persistence:
                            driver: orm
                            model: AppBundle\Entity\Band
                            finder: ~
                            provider:
                                service: app_bundle.provider.band_provider
                            listener:
                                logger: true
and get my desired result:

    {
        "took": 2,
        "timed_out": false,
        "_shards": {
            "total": 5,
            "successful": 5,
            "skipped": 0,
            "failed": 0
        },
        "hits": {
            "total": 4,
            "max_score": 1,
            "hits": [{
                    "_index": "music",
                    "_type": "band",
                    "_id": "2",
                    "_score": 1,
                    "_source": {
                        "id": "1",
                        "name": "Queen",
                        "album_id": "1",
                        "album_title": "The Works",
                        "track_id": "2",
                        "track_title": "Tear It Up",
                        "track_number": "2"
                    }
                },
    [...]

@The-Don-Himself Thanks for the links provided, I'll give them a try!

**Comment by XWB** [comment]
:+1:

**Comment by ahmed-bhs** [comment]
I think you just got your List of object from the database then transformed It to Elastic object ...you can use some function like ` $this->transformToElasticaDocument($object);`  but It's not the best solution because the process gonna take mush time to communicate with doctrine layer the transom the object to elastic Document.
