### ISSUE TITLE
Parameter indexable_callback doesn't seem to be used for updates

### ISSUE THREAD

**Issue by gregquat** [FriendsOfSymfony/FOSElasticaBundle#1351]
Hi,

The documentations says : "In all cases, the callback should return a true or false, with true indicating it will be indexed, and a false indicating the object should not be indexed, or should be removed from the index if we are running an update." (https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/types.md#testing-if-an-object-should-be-indexed)

But when I use this parameter with a populate command (with --no-reset option), the document is not remove neither updated.

1) In my Elastica configuration : 
`    indexable_callback: isPublic`

2) I have documents with the "public" property to true and some to false.
3) I run fos:elastica:populate, only the public documents are indexed. 
4) Some objects are unpublished (public = false) in database
5) I run fos:elastica:populate --no-reset
6) The unpublished documents are still indexed with the public property to true.

Is it a normal behaviour?
Thanks a lot

**Comment by cjost1988** [comment]
Hi,

I am facing the exact same issue, the mapping is referenced to my database entities by `ORM` driver but once I change an entity property that is marked at `indexable_callback` it will be persisted to elasticseach but not removed.

The documentation indicates that `should be removed from the index if we are running an update`. This issue is already open for over 2 years, so I guess this is still up2date.

Thanks,
Chris

**Comment by llupa** [comment]
Bump. 

I have the same behavior. Upon creation `indexable_callback` returns `true`. If a new data set is submitted and persisted, `indexable_callback` returns `false`. I can see that ForElastica events actually call it and they get a false but no remove action is performed.

**Comment by deguif** [comment]
@llupa could you dump your `fos_elastica` configuration here.
`indexable_callback` is only used with the doctrine listener.

**Comment by llupa** [comment]
@deguif thank you for pinging me so soon, but I fear I too wrote too soon. After some further digging (not so soon) I found out that my tests were checking for the removed item too soon. This feature works fine! 

I have version v5.1.1

Let's write soon! 😅

**Comment by FilipJanousek** [comment]
Hi, I have same problem too with parameter --no-reset. I also have documents out there that shouldn't be there because they don't get past the condition in function for populate (indexable). Everything is fine when I run without parameter --no-reset. I have version v5.1.1. Has anyone solved this problem?
