### ISSUE TITLE
MoreLikeThis query type doesn't work

### ISSUE THREAD

**Issue by aibragimov4xxi** [FriendsOfSymfony/FOSElasticaBundle#1353]
I'am trying to use ```Query\MoreLikeThis``` but it is not working.

I want to find all entities which contain string 'ips' (the part of word 'ipsa').
The Match query cant find it (because Match query try to find only full word).
So I need MoreLikeThis query. But it always returns empty result.

Does MoreLikeThis query even work? And how can I use it if it does?

**Comment by Tobion** [comment]
Closing as this issue is not related to FOSElasticaBundle. The MoreLikeThis query is provided by Elastica. But I'd recommend you to read the elasticsearch documentation as Elastica is just a client api for elasticsearch.

Btw, I don't think MoreLikeThis is necessarily what you are looking for. You can try out https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html for example which supports wildcards. Or you can try the `fuzziness` parameter for Match query.
