### ISSUE TITLE
index is created instead of alias on entity creation

### ISSUE THREAD

**Issue by hq9000** [FriendsOfSymfony/FOSElasticaBundle#1534]
we have an index called "leads", part of config of this index is:

  indexes:
    leads:
      use_alias: true
      index_name: leads

when running pupolate command it works as expected: alias and timestamped index are created. However, if there are some entities created **before** the creation of the alias (which triggers syncronization to elastic search), for some reason, an index called "leads" is appearing  (not alias).

are we doing anything wrongly or it is indeed a bug in the bundle?

**Comment by ga-tb** [comment]
I have the same problem.

When a single entity is modified, the app will look for an index called `leads`. If it can't find one, or it can't find an index with the alias of `leads`, it will create a new index.

```curl http://localhost:9200/_aliases | json_pp                       
{
   "leads" : {
      "aliases" : {
      }
   }
}
```

There's also another edge case: if your application has a working index + alias configuration, and you kick off a long running populate command, then elasticsearch will look like this...

```curl http://localhost:9200/_aliases | json_pp                       
{
   "leads_2019-09-25-100000" : { // current live search index
      "aliases" : {
        "leads" : {}
      }
   },
   "leads_2019-09-25-102000" : { // new populating search index
      "aliases" : {
      }
   }
}
```

Any publish requests received during this time will be sent to the current live index, `leads_2019-09-25-100000`.

After the populate command has finished and the aliases are swapped, those newly published changes will be lost as index `leads_2019-09-25-100000` is dropped.

**Comment by timching** [comment]
I have a similar problem
but my workaround is to run the `fos:elastica:create` command first to make sure the index/aliased index was created before the entity was saved.

Also beware, please use `^6.2.0` if you are using an alias in your setting, coz it used an incorrect alias name `<6.2.0`, see change log here https://github.com/timching/FOSElasticaBundle/blob/master/CHANGELOG-6.0.md#620-2022-08-31

I believe that this happens because the fos_elastica's listener config will be triggered once we save the entity.
