### ISSUE TITLE
Support for Symfony 5

### ISSUE THREAD

**Issue by mfeltscher** [FriendsOfSymfony/FOSElasticaBundle#1624]
Hi

Are there plans on supporting Symfony 5.x?

Thanks
Moreno

**Comment by oenie** [comment]
It looks like it was somehow merged into the 5.x branch, but that is behind the master branch ... any uptdates on that ?

**Comment by Growiel** [comment]
I just started a new project with SF5 and was suprised to see that Elastica doesn't support SF5, any updates on this ? Thanks.

**Comment by dboerger** [comment]
Same as Growiel trying a new project with SF, FOSElastic and API Platform, looks like there was a PR that added SF5 support, but somehow has since been removed:

https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1573

**Comment by dboerger** [comment]
Looks like https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1592 has a temporary solution, the dev branch has SF5 support, was able to successfully install with `composer require friendsofsymfony/elastica-bundle:5.x-dev`.  Hopefully this will be merged in with Master soon!

**Comment by olix21** [comment]
I wonder if we can help the maintainers in any way to bring Symfony 5 support on any of the stable releases (not one with a `-dev` tag)?

**Comment by olix21** [comment]
@XWB When you have time, can you inform us about your plans? Any stable release in mind?
And maybe check why the master branch does not have the "SF5 support" commit.
Maybe @jmikola can help too?

Sorry for pinging you guys, can we help in any way with something?

**Comment by jmikola** [comment]
> Maybe @jmikola can help too?

I've not contributed to this project [since 2013](https://github.com/FriendsOfSymfony/FOSElasticaBundle/commits?author=jmikola) so I'd have to defer to one of the active maintainers and/or [recent committers](https://github.com/FriendsOfSymfony/FOSElasticaBundle/commits/master).

**Comment by tacman** [comment]
I have a fork that worked for my needs with Symfony 5, and probably 4.4,
but not anything earlier.  I stopped working on it because I wanted to use
ES7, and am not sure it's complete.

The event that actually indexes a document should be handled by the
Messenger component.  It's a perfect use case for that, but it doesn't
exist in earlier versions of Symfony.

So part of the issue that blocks moving to Symfony 5 keeping support for
Symfony 3.4.  One solution is to add bump master only handle 4.4+, and
create a new release branch of version 6, consistent with the current
approach to versions:

https://github.com/FriendsOfSymfony/FOSElasticaBundle#versions--dependencies

That seems like a short-term solution, though, since we'd almost
immediately need to start working on version 7 that supports ES7, with
significant changes (no BC promises).

Of course, these are just my musings.  But I'm sure all of us on this
thread would like to hear the vision of the active maintainers.

Tac

**Comment by localheinz** [comment]
Related to #1602.

**Comment by XWB** [comment]
Symfony 5 support has been added to the master branch.
