### ISSUE TITLE
split word in term facet

### ISSUE THREAD

**Issue by MonkeyDDude** [FriendsOfSymfony/FOSElasticaBundle#867]
When I create a facet on a string field,
if the value is "4/3", the facet return 2 values "4" and "3".

How can I configure elastica in order to have "4/3" on value ?

**Comment by merk** [comment]
Support for use of Elastica and ElasticSearch should go in their repositories. (we provide the glue to symfony)

As for your issue i suspect it is because / must be escaped. Check out the Util classes in Elastica which can escape stuff, otherwise try doing direct queries against ElasticSearch to work out if there is a problem with Elastica's interpretation of the queries you're trying to use.
