### ISSUE TITLE
Queries generated by the Doctrine ORM Provider slow down untill they are processing < 1 obj/s

### ISSUE THREAD

**Issue by ebernhardson** [FriendsOfSymfony/FOSElasticaBundle#87]
Our use case is indexing a table from mysql that has ~ 10M rows.

The queries generated by the orm provider look like

SELECT ...  FROM Customer c0_ LIMIT 100 OFFSET 141300
SELECT ...  FROM Customer c0_ LIMIT 100 OFFSET 141400
SELECT ...  FROM Customer c0_ LIMIT 100 OFFSET 141500
SELECT ...  FROM Customer c0_ LIMIT 100 OFFSET 141600
SELECT ...  FROM Customer c0_ LIMIT 100 OFFSET 141700

This query means that most sql servers will have to walk through the result set to return 100 items, horribly inefficient and will never finish on a table with 10M rows.

I propose the queries issued via ORM should use

Query::iterate(), along with $this->objectManager->detach() for each returned object.

**Comment by adrian410** [comment]
Hi @cmodijk,

I'm very impressed with your results. I have to add 2million entries and i have at least 4Go everytime.
I'm on 3.1 version.

I would like to use your custom provier : https://gist.github.com/cmodijk/9259470
But how do you add it , how do you specify to elasticabundle to use this provider ?

It will help me so much.

Thanks,
Adrian.

**Comment by merk** [comment]
Are you doing the population in the prod env without debugging mode enabled? The default provider does almost the same (except the replacement of LIMIT/OFFSET) as cmodijk's provider.

**Comment by adrian410** [comment]
Hi @merk,
I updated my version of the bundle and used the following command : 
php app/console fos:elastica:populate --no-reset --index=afsy --type=Artist --no-debug --offset=n

I haven't got a leak since. And I'm getting around 30-50Mo.

But i have another issue, i use a custom provider for my entities with a huge query, and a lot of "JOIN". I'm getting the same row mutliple times, which is normal.

So i tried to add a DISTINCT and GROUP BY to delete the duplicate rows.
But i have this error : " [Doctrine\ORM\NonUniqueResultException] ".

I tracked the error and it came from the function "countObjects" in Provider.php.

If i dont put the GROUP BY/ DISTINCT i get a very long populate.

Do you have a solution ?

Sorry for my english.
Thanks,
Adrian.

**Comment by johnpez** [comment]
Using elasticsearch 3.1.x there are now some issues with this gist.

First off, php throws a warning due to the new progress bar method of the progress builder bar.

The one I can't figure out is that the custom provider is used if I rebuild my entire index, but if I select a document type using the commands --index=indexName --type=typeName then the custom provider is not used.

Any thoughts why this might be and how to make sure it's used?

Thanks a bunch

**Comment by merk** [comment]
Could you please create a new issue with more information about your configuration (service configurations, fos_elastica configuration) ?
